### ISSUE TITLE
[QUESTION] how to send ReadableStream<Uint8Array>?

### ISSUE THREAD

**Issue by mattn** [cmorten/opine#169] opened 2022-06-25 18:42 UTC
I'm trying to send image data which is given from S3 using [deno_s3](https://github.com/lucacasonato/deno_s3/) like below.

```typescript
    const obj = await bucket.getObject("xxx.png");
    //const b = await new Response(obj?.body).text();
    // how to send obj without read whole data on memory.
    res.type("image/png").send(b);
```

Can I get this?

**Comment by cmorten** [comment] 2022-08-27 08:55
Opine is using the Deno std library for responding to requests, which in turn makes use of the `Response` Web API which supports `ReadableStream<Uint8Array>` for it's `ResponseInit` https://github.com/cmorten/opine/blob/main/src/request.ts#L88

Is `res.send()` not working for you? If you can share an error etc. this would be useful.

**Comment by cmorten** [comment] 2022-08-27 09:00
I _think_ I've pushed a fix so you can pass `ReadableStream` to `res.send()` please could you test it out and confirm?

Failing that it might be worth trying to pass to `res.end()` directly.

Please reopen if the issue isn't resolved in https://github.com/cmorten/opine/releases/tag/2.3.3.

**Closed by cmorten** 2022-08-27 09:00 UTC
